=== tilluhlig/sqalibur-xsltRules/src/main/java/com/sqalibur/transformationrules/definitions/baum.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
           elementFormDefault="qualified"
           vc:minVersion="1.0" vc:maxVersion="1.1">
    
    <!-- die Wurzel des Baums -->
    <xs:element name="root" type="node"/>
    
    <!-- der allgemeine Knotentyp -->
    <xs:complexType name="node">
        <xs:sequence>
            <xs:element
                name="node" type="node"
                minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute
            name="label" type="xs:string" use="optional"/>
        <xs:attribute
            name="class" type="xs:string" use="optional"
            default="const"/>
        <xs:attribute
            name="signature" type="xs:string" use="optional"/>
    </xs:complexType>
</xs:schema>

=== tilluhlig/sqalibur-xsltRules/src/main/java/com/sqalibur/xsltrules/examples/sampleResult.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="baum.xsd">
    <!-- Eingabe: not not not ((a>5) and ((b>5) or (c>5 or d>5)))-->
    <node label="and" class="binop">
        <node label="or" class="binop">
            <node label="not" class="unop">
                <node label="&gt;" class="binop">
                    <node label="a"/>
                    <node label="5"/>
                </node>
            </node>
            <node label="not" class="unop">
                <node label="&gt;" class="binop">
                    <node label="b"/>
                    <node label="5"/>
                </node>
            </node>
        </node>
        <node label="or" class="binop">
            <node label="not" class="unop">
                <node label="&gt;" class="binop">
                    <node label="a"/>
                    <node label="5"/>
                </node>
            </node>
            <node label="not" class="unop">
                <node label="&gt;" class="binop">
                    <node label="c"/>
                    <node label="5"/>
                </node>
            </node>
        </node>
        <node label="or" class="binop">
            <node label="not" class="unop">
                <node label="&gt;" class="binop">
                    <node label="a"/>
                    <node label="5"/>
                </node>
            </node>
            <node label="not" class="unop">
                <node label="&gt;" class="binop">
                    <node label="d"/>
                    <node label="5"/>
                </node>
            </node>
        </node>
    </node>
</root>

=== tilluhlig/sqalibur-xsltRules/src/main/java/com/sqalibur/transformationrules/examples/sample.xml
<?xml version="1.0" encoding="UTF-8"?><root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="baum.xsd">
    
    <!-- Eingabe: not not not ((a>5) and ((b>5) or (c>5 or d>5)))-->
    <node label="not" class="unop">
        <node label="not" class="unop">
            <node label="not" class="unop">
                <node label="and" class="binop">
                    <node label="&gt;" class="binop">
                        <node label="a"/>asd
                        <node label="5"/>
                    </node>
                    <node label="or" class="binop">
                        <node label="&gt;" class="binop">
                            <node label="b"/>
                            <node label="5"/>
                        </node>
                        <node label="or" class="binop">
                            <node label="&gt;" class="binop">
                                <node label="c"/>
                                <node label="5"/>
                            </node>
                            <node label="&gt;" class="binop">
                                <node label="d"/>
                                <node label="5"/>
                            </node>
                        </node>
                    </node>
                </node>
            </node>
        </node>
    </node>
</root>
